In [20]:
import pandas as pd
import numpy as np

In [21]:
#Load Dataset
listings = pd.read_csv("../data/raw/listings.csv")
calendar = pd.read_csv("../data/raw/calendar.csv")
reviews = pd.read_csv("../data/raw/reviews.csv")
neighbourhoods = pd.read_csv("../data/raw/neighbourhoods.csv")

In [22]:
#View First Records
listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,71609,https://www.airbnb.com/rooms/71609,20260629151954,2026-07-02,previous scrape,Ensuite Room (Room 1 & 2) near EXPO,For 3 rooms.Book room 1&2 and room 4,NaN,https://a0.muscache.com/pictures/24453191/3580...,367042,...,4.78,4.26,4.32,NaN,NaN,5,0,5,0,0.11
1,71896,https://www.airbnb.com/rooms/71896,20260629151954,2026-07-02,previous scrape,B&B Room 1 near Airport & EXPO,NaN,NaN,https://a0.muscache.com/pictures/2440674/ac4f4...,367042,...,4.43,4.17,4.04,NaN,NaN,5,0,5,0,0.13
2,71903,https://www.airbnb.com/rooms/71903,20260629151954,2026-07-02,previous scrape,Room 2-near Airport & EXPO,"Like your own home, 24hrs access.",NaN,https://a0.muscache.com/pictures/568743/7bc623...,367042,...,4.64,4.50,4.36,NaN,NaN,5,0,5,0,0.25
3,294281,https://www.airbnb.com/rooms/294281,20260629151954,2026-07-02,previous scrape,5 mins walk from Newton subway,I have 3 bedrooms in a charming British style...,NaN,https://a0.muscache.com/pictures/4607862/87f42...,1521514,...,4.66,4.52,4.39,NaN,NaN,7,1,6,0,0.75
4,344803,https://www.airbnb.com/rooms/344803,20260629151954,2026-07-02,previous scrape,Budget short stay room near EXPO,Direct bus 24 from airport to this place.Walki...,NaN,https://a0.muscache.com/pictures/4240c88e-4dc2...,367042,...,4.58,4.66,4.44,NaN,NaN,5,0,5,0,0.34

In [23]:
calendar.head()

   listing_id        date available  minimum_nights  maximum_nights
0       71609  2026-07-02         f              92            1125
1       71609  2026-07-03         t              92            1125
2       71609  2026-07-04         t              92            1125
3       71609  2026-07-05         t              92            1125
4       71609  2026-07-06         t              92            1125

In [24]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,71609,793880,2011-12-19,1456140,Max,The rooms were clean and tidy. Beds very comfo...
1,71609,1731810,2012-07-17,1804182,Jaiya,Good space and quite an interesting home in a ...
2,71609,2162194,2012-09-01,3113461,Zahra,It was a comfortable place. Belinda was a kind...
3,71609,2190615,2012-09-04,1432123,Helmut,We are four mature age travellers and stayed f...
4,71609,3221837,2013-01-02,2759938,Jack,Belinda is a great host! She helps you wheneve...

In [25]:
neighbourhoods.head()

  neighbourhood_group  neighbourhood
0      Central Region         Bishan
1      Central Region    Bukit Merah
2      Central Region    Bukit Timah
3      Central Region  Downtown Core
4      Central Region        Geylang

In [26]:
#Check Dataset Size
listings.shape
calendar.shape
reviews.shape
neighbourhoods.shape

(55, 2)

Listings Details

In [27]:
#Column Names
listings.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

In [28]:
#Data Types
listings.dtypes

id                                                int64
listing_url                                         str
scrape_id                                         int64
last_scraped                                        str
source                                              str
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 90, dtype: object

In [29]:
#Missing Values
listings.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1361
Length: 90, dtype: int64

In [30]:
missing = listings.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

neighborhood_overview          3097
host_thumbnail_url             3097
host_since                     3097
host_acceptance_rate           3097
host_response_rate             3097
host_response_time             3097
instant_bookable               3097
neighbourhood                  3097
host_verifications             3097
host_total_listings_count      3097
host_neighbourhood             3097
calendar_updated               3097
bathrooms                      1945
beds                           1807
review_scores_value            1362
review_scores_location         1362
review_scores_rating           1361
review_scores_accuracy         1361
first_review                   1361
reviews_per_month              1361
review_scores_cleanliness      1361
review_scores_checkin          1361
review_scores_communication    1361
last_review                    1361
license                        1356
host_location                  1155
bedrooms                       1141
host_about                     1129
price                           505
price_quote_price_per_night     505
estimated_revenue_l365d         505
price_quote_total_price         505
price_quote_checkout_date       310
price_quote_raw                 310
price_quote_checkin_date        310
description                     179
host_profile_url                 69
hosts_time_as_host_months        59
host_is_superhost                59
hosts_time_as_user_years         59
hosts_time_as_user_months        59
hosts_time_as_host_years         59
host_name                        59
host_identity_verified           59
host_picture_url                 59
host_profile_id                  59
host_has_profile_pic             59
host_listings_count              59
has_availability                 42
bathrooms_text                   10
picture_url                       3
dtype: int64

In [31]:
#Duplicate Rows
listings.duplicated().sum()

np.int64(0)

In [32]:
#Summary Statistics
listings.describe()

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.097000e+03,3.097000e+03,0.0,3.097000e+03,3.038000e+03,0.0,3038.000000,3038.000000,3038.000000,3038.000000,...,1736.000000,1736.000000,1735.000000,1735.000000,0.0,3097.000000,3097.000000,3097.000000,3097.000000,1736.000000
mean,6.873474e+17,2.026063e+13,NaN,8.806882e+15,1.470873e+18,NaN,8.000329,5.878209,7.288677,5.791310,...,4.743681,4.707419,4.699718,4.433470,NaN,41.988699,29.250888,12.279303,0.203423,0.513053
std,6.418462e+17,0.000000e+00,NaN,1.222308e+17,2.768292e+16,NaN,3.863194,3.400640,3.930489,3.364465,...,0.468692,0.569365,0.456945,0.648207,NaN,58.224823,58.647779,20.276715,1.256488,1.341256
min,7.160900e+04,2.026063e+13,NaN,2.182320e+05,1.462513e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.615609e+07,2.026063e+13,NaN,2.903270e+07,1.462959e+18,NaN,6.000000,3.000000,4.000000,3.000000,...,4.670000,4.670000,4.600000,4.185000,NaN,4.000000,0.000000,1.000000,0.000000,0.040000
50%,8.103768e+17,2.026063e+13,NaN,1.352988e+08,1.465699e+18,NaN,9.000000,6.000000,8.000000,6.000000,...,4.935000,4.920000,4.860000,4.600000,NaN,11.000000,1.000000,4.000000,0.000000,0.150000
75%,1.341702e+18,2.026063e+13,NaN,3.333227e+08,1.469398e+18,NaN,11.000000,8.000000,10.000000,8.000000,...,5.000000,5.000000,5.000000,4.905000,NaN,64.000000,34.000000,14.000000,0.000000,0.450000
max,1.716878e+18,2.026063e+13,NaN,1.706906e+18,1.716723e+18,NaN,15.000000,11.000000,15.000000,11.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,215.000000,215.000000,89.000000,13.000000,23.100000

In [33]:
#Dataset Information
listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 3097 entries, 0 to 3096
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            3097 non-null   int64
 1   listing_url                                   3097 non-null   str
 2   scrape_id                                     3097 non-null   int64
 3   last_scraped                                  3097 non-null   str
 4   source                                        3097 non-null   str
 5   name                                          3097 non-null   str
 6   description                                   2918 non-null   str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   3094 non-null   str
 9   host_id                                       3097 non-null   int64
 10  host_url                                      3097 non-null   str
 11  host_profile_id                               3038 non-null   float64
 12  host_profile_url                              3028 non-null   str
 13  host_name                                     3038 non-null   str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      3038 non-null   float64
 16  hosts_time_as_user_months                     3038 non-null   float64
 17  hosts_time_as_host_years                      3038 non-null   float64
 18  hosts_time_as_host_months                     3038 non-null   float64
 19  host_location                                 1942 non-null   str
 20  host_about                                    1968 non-null   str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             3038 non-null   str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              3038 non-null   str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           3038 non-null   float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          3038 non-null   str
 32  host_identity_verified                        3038 non-null   str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        3097 non-null   str
 35  neighbourhood_group_cleansed                  3097 non-null   str
 36  latitude                                      3097 non-null   float64
 37  longitude                                     3097 non-null   float64
 38  property_type                                 3097 non-null   str
 39  room_type                                     3097 non-null   str
 40  accommodates                                  3097 non-null   int64
 41  bathrooms                                     1152 non-null   float64
 42  bathrooms_text                                3087 non-null   str
 43  bedrooms                                      1956 non-null   float64
 44  beds                                          1290 non-null   float64
 45  amenities                                     3097 non-null   str
 46  price                                         2592 non-null   str
 47  price_quote_checkin_date                      2787 non-null   str
 48  price_quote_checkout_date                     2787 non-null   str
 49  price_quote_total_price                       2592 non-null   float64
 50  price_quote_price_per_night                   2592 non-null   float64
 51  price_quote_raw                               2787 non-null   str
 52  minimum_nights                                3097 non-null   int64
 53  maximum_nights                                3097 non-null   int64
 54  minimum_minimum_nights                        3097 non-null   int64
 55  maximum_minimum_nights                        3097 non-null   int64
 56  minimum_maximum_nights                        3097 non-null   int64
 57  maximum_maximum_nights                        3097 non-null   int64
 58  minimum_nights_avg_ntm                        3097 non-null   float64
 59  maximum_nights_avg_ntm                        3097 non-null   float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              3055 non-null   str
 62  availability_30                               3097 non-null   int64
 63  availability_60                               3097 non-null   int64
 64  availability_90                               3097 non-null   int64
 65  availability_365                              3097 non-null   int64
 66  calendar_last_scraped                         3097 non-null   str
 67  number_of_reviews                             3097 non-null   int64
 68  number_of_reviews_ltm                         3097 non-null   int64
 69  number_of_reviews_l30d                        3097 non-null   int64
 70  availability_eoy                              3097 non-null   int64
 71  number_of_reviews_ly                          3097 non-null   int64
 72  estimated_occupancy_l365d                     3097 non-null   int64
 73  estimated_revenue_l365d                       2592 non-null   float64
 74  first_review                                  1736 non-null   str
 75  last_review                                   1736 non-null   str
 76  review_scores_rating                          1736 non-null   float64
 77  review_scores_accuracy                        1736 non-null   float64
 78  review_scores_cleanliness                     1736 non-null   float64
 79  review_scores_checkin                         1736 non-null   float64
 80  review_scores_communication                   1736 non-null   float64
 81  review_scores_location                        1735 non-null   float64
 82  review_scores_value                           1735 non-null   float64
 83  license                                       1741 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                3097 non-null   int64
 86  calculated_host_listings_count_entire_homes   3097 non-null   int64
 87  calculated_host_listings_count_private_rooms  3097 non-null   int64
 88  calculated_host_listings_count_shared_rooms   3097 non-null   int64
 89  reviews_per_month                             1736 non-null   float64
dtypes: float64(36), int64(24), str(30)
memory usage: 8.5 MB

In [34]:
#Create Data Quality Summary
quality = pd.DataFrame({
    "Rows":[listings.shape[0]],
    "Columns":[listings.shape[1]],
    "Missing":[listings.isnull().sum().sum()],
    "Duplicates":[listings.duplicated().sum()]
})

quality

   Rows  Columns  Missing  Duplicates
0  3097       90    63211           0

Calendar details

In [36]:
#Column Names
calendar.columns

Index(['listing_id', 'date', 'available', 'minimum_nights', 'maximum_nights'], dtype='str')

In [37]:
#Data Types
calendar.dtypes

listing_id        int64
date                str
available           str
minimum_nights    int64
maximum_nights    int64
dtype: object

In [38]:
#Missing Values
calendar.isnull().sum()

listing_id        0
date              0
available         0
minimum_nights    0
maximum_nights    0
dtype: int64

In [39]:
missing = calendar.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [40]:
#Duplicate Rows
calendar.duplicated().sum()

np.int64(0)

In [41]:
#Summary Statistics
calendar.describe()

         listing_id  minimum_nights  maximum_nights
count  1.185155e+06    1.185155e+06    1.185155e+06
mean   7.228868e+17    5.021724e+01    6.527436e+02
std    6.475066e+17    5.359501e+01    7.237694e+02
min    7.160900e+04    1.000000e+00    1.000000e+00
25%    3.798167e+07    2.000000e+00    3.650000e+02
50%    8.591716e+17    2.800000e+01    3.650000e+02
75%    1.370784e+18    9.200000e+01    1.125000e+03
max    1.716878e+18    7.300000e+02    9.999000e+03

In [42]:
#Dataset Information
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1185155 entries, 0 to 1185154
Data columns (total 5 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   listing_id      1185155 non-null  int64
 1   date            1185155 non-null  str
 2   available       1185155 non-null  str
 3   minimum_nights  1185155 non-null  int64
 4   maximum_nights  1185155 non-null  int64
dtypes: int64(3), str(2)
memory usage: 57.6 MB

In [43]:
#Create Data Quality Summary
quality = pd.DataFrame({
    "Rows":[calendar.shape[0]],
    "Columns":[calendar.shape[1]],
    "Missing":[calendar.isnull().sum().sum()],
    "Duplicates":[calendar.duplicated().sum()]
})

quality

      Rows  Columns  Missing  Duplicates
0  1185155        5        0           0

Reviews Details

In [44]:
#Column Names
reviews.columns

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='str')

In [45]:
#Data Types
reviews.dtypes

listing_id       int64
id               int64
date               str
reviewer_id      int64
reviewer_name      str
comments           str
dtype: object

In [46]:
#Missing Values
reviews.isnull().sum()

listing_id        0
id                0
date              0
reviewer_id       0
reviewer_name     0
comments         17
dtype: int64

In [47]:
missing = reviews.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

comments    17
dtype: int64

In [48]:
#Duplicate Rows
reviews.duplicated().sum()

np.int64(0)

In [49]:
#Summary Statistics
reviews.describe()

         listing_id            id   reviewer_id
count  4.126500e+04  4.126500e+04  4.126500e+04
mean   3.324451e+17  7.726038e+17  1.383238e+15
std    5.460834e+17  6.598224e+17  4.817070e+16
min    7.160900e+04  2.514670e+05  1.492200e+04
25%    1.792817e+07  4.794364e+08  5.133029e+07
50%    4.207954e+07  8.945465e+17  1.493527e+08
75%    7.497588e+17  1.412810e+18  3.412095e+08
max    1.675861e+18  1.718692e+18  1.708357e+18

In [50]:
#Dataset Information
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 41265 entries, 0 to 41264
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     41265 non-null  int64
 1   id             41265 non-null  int64
 2   date           41265 non-null  str
 3   reviewer_id    41265 non-null  int64
 4   reviewer_name  41265 non-null  str
 5   comments       41248 non-null  str
dtypes: int64(3), str(3)
memory usage: 11.2 MB

In [51]:
#Create Data Quality Summary
quality = pd.DataFrame({
    "Rows":[reviews.shape[0]],
    "Columns":[reviews.shape[1]],
    "Missing":[reviews.isnull().sum().sum()],
    "Duplicates":[reviews.duplicated().sum()]
})

quality

    Rows  Columns  Missing  Duplicates
0  41265        6       17           0

Neighbourhoods Details

In [52]:
#Column Names
neighbourhoods.columns

Index(['neighbourhood_group', 'neighbourhood'], dtype='str')

In [54]:
#Data Types
neighbourhoods.dtypes

neighbourhood_group    str
neighbourhood          str
dtype: object

In [55]:
#Missing Values
neighbourhoods.isnull().sum()

neighbourhood_group    0
neighbourhood          0
dtype: int64

In [56]:
missing = neighbourhoods.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [57]:
#Duplicate Rows
neighbourhoods.duplicated().sum()

np.int64(0)

In [58]:
#Summary Statistics
neighbourhoods.describe()

       neighbourhood_group neighbourhood
count                   55            55
unique                   5            55
top         Central Region        Bishan
freq                    22             1

In [59]:
#Dataset Information
neighbourhoods.info()

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  55 non-null     str
 1   neighbourhood        55 non-null     str
dtypes: str(2)
memory usage: 2.2 KB

In [60]:
#Create Data Quality Summary
quality = pd.DataFrame({
    "Rows":[neighbourhoods.shape[0]],
    "Columns":[neighbourhoods.shape[1]],
    "Missing":[neighbourhoods.isnull().sum().sum()],
    "Duplicates":[neighbourhoods.duplicated().sum()]
})

quality

   Rows  Columns  Missing  Duplicates
0    55        2        0           0